"""Add container, volume, and config models for pod enhancements

Revision ID: 09a7b48160ca
Revises: 889938955a0a
Create Date: 2025-04-02 15:39:53.880267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a7b48160ca'
down_revision = '889938955a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('config_type', sa.String(length=20), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.Column('cpu_req', sa.Float(), nullable=True),
    sa.Column('memory_req', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=200), nullable=True),
    sa.Column('args', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('volume_type', sa.String(length=20), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('pod_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('has_volumes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_config', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.drop_column('has_config')
        batch_op.drop_column('has_volumes')
        batch_op.drop_column('pod_type')
        batch_op.drop_column('ip_address')

    op.drop_table('volumes')
    op.drop_table('containers')
    op.drop_table('config_items')
    # ### end Alembic commands ###
