"""Initial migration

Revision ID: 889938955a0a
Revises: 
Create Date: 2025-04-02 15:30:16.952393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889938955a0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=True),
    sa.Column('cpu_cores_avail', sa.Integer(), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('kubelet_status', sa.String(length=20), nullable=True),
    sa.Column('container_runtime_status', sa.String(length=20), nullable=True),
    sa.Column('kube_proxy_status', sa.String(length=20), nullable=True),
    sa.Column('node_agent_status', sa.String(length=20), nullable=True),
    sa.Column('api_server_status', sa.String(length=20), nullable=True),
    sa.Column('scheduler_status', sa.String(length=20), nullable=True),
    sa.Column('controller_status', sa.String(length=20), nullable=True),
    sa.Column('etcd_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('cpu_cores_req', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pods')
    op.drop_table('nodes')
    # ### end Alembic commands ###
