"""Add Docker fields to Container table

Revision ID: 943b4331d57f
Revises: 09a7b48160ca
Create Date: 2025-04-02 16:39:16.703667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943b4331d57f'
down_revision = '09a7b48160ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docker_container_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('docker_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('exit_code', sa.Integer(), nullable=True))

    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docker_network_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docker_volume_name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.drop_column('docker_volume_name')

    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.drop_column('docker_network_id')

    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_column('exit_code')
        batch_op.drop_column('docker_status')
        batch_op.drop_column('docker_container_id')

    # ### end Alembic commands ###
