"""Initial migration

Revision ID: ca56acd7fa36
Revises: 
Create Date: 2025-04-05 14:22:29.055858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca56acd7fa36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=True),
    sa.Column('cpu_cores_avail', sa.Integer(), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('kubelet_status', sa.String(length=20), nullable=True),
    sa.Column('container_runtime_status', sa.String(length=20), nullable=True),
    sa.Column('kube_proxy_status', sa.String(length=20), nullable=True),
    sa.Column('node_agent_status', sa.String(length=20), nullable=True),
    sa.Column('api_server_status', sa.String(length=20), nullable=True),
    sa.Column('scheduler_status', sa.String(length=20), nullable=True),
    sa.Column('controller_status', sa.String(length=20), nullable=True),
    sa.Column('etcd_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('cpu_cores_req', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('pod_type', sa.String(length=20), nullable=True),
    sa.Column('has_volumes', sa.Boolean(), nullable=True),
    sa.Column('has_config', sa.Boolean(), nullable=True),
    sa.Column('docker_network_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('config_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('config_type', sa.String(length=20), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.Column('cpu_req', sa.Float(), nullable=True),
    sa.Column('memory_req', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=200), nullable=True),
    sa.Column('args', sa.String(length=200), nullable=True),
    sa.Column('docker_container_id', sa.String(length=64), nullable=True),
    sa.Column('docker_status', sa.String(length=20), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('volume_type', sa.String(length=20), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.Column('docker_volume_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volumes')
    op.drop_table('containers')
    op.drop_table('config_items')
    op.drop_table('pods')
    op.drop_table('nodes')
    # ### end Alembic commands ###
